# This is a basic workflow to help you get started with Actions

name: DESY Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - 'src/app_demo/hdl/app_demo_top.vhd'
  pull_request:
    paths:
      - 'src/app_demo/hdl/app_demo_top.vhd'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  adder_test:
    # The type of runner that the job will run on
    runs-on: self-hosted

    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v4

      - name: run test
        run: |
          source setup.sh
          make cfg=cocotb cocotb
          make cfg=cocotb cocotb_sim
          ! grep "failure" prj/demo_cocotb_default/results.xml
